### ISSUE TITLE
Adding AnalysisResult

### ISSUE THREAD

**Issue by hampusnasstrom** [FAIRmat-NFDI/nomad-analysis#34]
We want to add `AnalysisResult(Entity)` and methods for creating and linking these with `AnalysisStep`s inside `Analysis`.
Additionally these methods should be able to run from an ipynb.

![Screenshot from 2024-09-18 11-43-39](https://github.com/user-attachments/assets/be67e00a-5e16-4479-a44d-b1b8454338f3)

**Comment by ka-sarthak** [comment]
`ActivityStep` is not defined in the base sections. As discussed, we can add a minimal section in `nomad_analysis.general`. I thought of handling this in a separate issue, but it pans out better to do it together in this issue.

I also experimented with the modification of entry archives via notebook. The steps I followed -
- Using the entry_id of the `ELNGenericJupyterAnalysis` entry (which is already available as a variable in the notebook), get the archive data dict via API
- Modify the dict
- overwrite the `archive.json` using the modified dict.

this works in principle. We can even compose `AnalysisResult` objects in the notebook and copy their data into the archive dict. We should also be able to use `ArchiveQuery` to get parsed `Analysis` objects directly. And then compose the `AnalysisResult` in the object, before using  `m_to_dict()`, and overwrite the archive. 

However, some issues here:
- JupyterHub environment at the moment does not have the plugins installed. So if we want to use the classes from nomad_analysis, we need to pip-install the package. this can be fixed by already installing the existing plugins in the oasis to the JupyterHub image during oasis deployment. @blueraft already have some PR in the distribution template for this https://github.com/FAIRmat-NFDI/nomad-distribution-template/pull/23

- When the archive.json is overwritten, the changes do not show up in the entry GUI. User needs to manually reprocess the upload folder to sync the changes there. If possible we should avoid this by triggering a reprocess automatically, right after the JSON is overwritten.  
  If, however, the user does not reprocess the upload, and instead open the entry and use the normalize button inside the entry, the overwritten changes will be reverted back: The GUI version of data prevails over the `archive.json`.

**Comment by ka-sarthak** [comment]
I tried to break down the issue into some actionable. @hampusnasstrom what do you think?

- Add minimal sections `AnalysisStep`, `AnalysisResult` to set up a data framework

- A predefined function for the notebook code block. It returns an instance of the current `ELNJupyterAnalysis` entry. The user can use this instance to compose the analysis step or result using the following methods.

- Instance methods for `ELNJupyterAnalysis`
  - `_create_result_entry(result: AnalysisResult)`:
    a private method that creates an entry for the AnalysisResult section and returns a proxy reference to it.  
  
  - `set_result(step_name: str, results: Union[AnalysisResult, list[AnalysisResult]])`: 
    used to set a result (or results) for an analysis step. If the step exists, it overwrites the `results`, else it creates a new step with the specified `step_name`. It uses `_create_result_entry` method to generate entries and append their references to `AnalysisStep.results`. 
  
    This allows the user to only bother with instances of `AnalysisResult`, and set them directly into the `AnalysisStep`, instead of dealing with entry and reference creation for the results.
  
  - `set_step(step: Union[AnalysisStep, list[AnalysisStep]])`:
    used to one or a list of analysis steps. 
  
  - `update_mainfile()`: 
    overwrite the mainfile `archive.json` file with the data from the current state of the class instance.

**Comment by hampusnasstrom** [comment]
@ka-sarthak sounds like a good start although I don't think we need to the `set_result` and `set_step` methods. I think those can just be added directly to the `AnalysisResult` object.

**Comment by ka-sarthak** [comment]
@hampusnasstrom I see. My thought was to have a method interface for the most common interactions that the user might have. Although I agree that this can be redundant, especially for `set_step`.

But the `set_result` method can be useful. It does a bit more than just setting the result. The user can create instances of `AnalysisResult` and simply push to the `ELNJupyterAnalysis`. The `set_result` takes care about creating an entry for the `AnalysisResult` and saving a section reference in `ELNJupyterAnalysis`.

```py
from nomad_analysis.general import AnalysisResult, AnalysisStep

analysis = get_analysis_entry_obj(...) 
# a function that uses nomad API to get an object of the current analysis entry

## assume this class is defined in the meta info via some plugin or custom schema
## for sake of argument
class PeakFittingAnalysisResult(AnalysisResult):
  peaks: list(Tuple(float, float))

peak_fit_res = PeakFittingAnalysisResult(peaks = [(i1, w1),(i2, w2)])

analysis.set_result(step_name='Peak Fitting', peak_fit_res)
# creates an entry and corresponding reference for PeakFittingAnalysisResult section
# creates an analysis step and add the reference as it's result

print(analysis.steps[0].results) # outputs: [SectionReference]
print(analysis.steps[0].name)   # outputs: "Peak Fitting"

```
Here I am assuming these definitions for the general classes https://github.com/FAIRmat-NFDI/nomad-analysis/pull/38/commits/fb4e3fa7ed4a5044835fa496879ea3b71a3a9f31#diff-30acc35db13ba78b00082cb886de248c9eb054ddfa3a0b85b97b51949b01bb78R36

**Comment by hampusnasstrom** [comment]
Sure, but it's yet another function that needs documentation. Not much more code to write:
```py
analysis.steps.append(AnalysisStep(name='Peak Fitting', result=peak_fit_res))
```
than
```py
analysis.set_result(step_name='Peak Fitting', peak_fit_res)
```
but we can support both if you feel it's useful.

**Comment by ka-sarthak** [comment]
Ah, but I thought `AnalysisStep.results` is to be defined as a reference to the `AnalysisResult` entry, not as `AnalysisResult` itself. Isn't that how we depict in the diagram? 

My interpretation is that `raw_result.archive.json` is generated with `m_def` of `AnalysisResult`. Then, a reference is saved in the `analysis.step[i].results` pointing to this entry. 

I envisioned `set_result` method to handle this entry creation. Am I missing something?

**Comment by hampusnasstrom** [comment]
Fine, you can nest it two steps deeper if you want. Same story:
```py
analysis.steps.append(
    AnalysisStep(
        name='Peak Fitting',
        results=[
            AnalysisResultReference(reference=peak_fit_res)
        ]
    )
)
```

**Comment by hampusnasstrom** [comment]
At least I think this will work. And then we just need to generate that archive on serialization. I know for sure it works the other way around. Any references will get resolved and be accessible as if they were composed in NOMAD. Something to investigate.

**Comment by ka-sarthak** [comment]
After the joint meeting for analysis with other groups, following suggestions were made:
- Markus suggested to have AnalyisResult as a sub-section rather than an entry. Processing of sub-sections is more efficient than processing of entries
- Use a consolidated entry containing definitions of multiple properties, can be called `CorrelatedProperties`. It makes references to samples, measurements, analysis results sub-section.

Keeping these in mind, I am making the following changes:
- Define AnalysisResult(Entity) and AnalysisStep(ActivityStep). `AnalysisStep.results` is defined as a `list[AnalysisResult]`
- Add `create_entry` function: Takes a section, URL, upload_id, and creates an entry. If the entry already exists, it overwrites it. This function will enable the functionality of `set_result`, `set_step`, `update_mainfile` all in one.

**Comment by JosePizarro3** [comment]
I have the feeling that `AnalysisResults` is just a sub-class of what we have in the nomad-simulations schema, `Outputs` (which is the practical implementation of the interoperability TF). Everything you said about correlated properties is something we would like to define better from our side (we have something, but not so good), but maybe you can take some of our defs for the analysis repo.

Should we have a chat @ka-sarthak @hampusnasstrom ? There are some details here about when there is a list of results and when a list of properties I would like to talk about.

**Comment by ka-sarthak** [comment]
@JosePizarro3 Can you point to the repo where the definitions for correlated properties are available?

Sure, a meeting would be great!

**Comment by JosePizarro3** [comment]
> @JosePizarro3 Can you point to the repo where the definitions for correlated properties are available?
> 
> Sure, a meeting would be great!

You can check the `Outputs` section [here](https://github.com/nomad-coe/nomad-simulations/blob/develop/src/nomad_simulations/schema_packages/outputs.py) and the `PhysicalProperty` [here](https://github.com/nomad-coe/nomad-simulations/blob/develop/src/nomad_simulations/schema_packages/physical_property.py#L69).

Our correlated properties concept is having a quantity called `PhysicalProperty.physical_property_ref` in case a property is extracted from another one. We have an extra `PhysicalProperty.is_derived` boolean to address this, but both are equivalent anyways.

Now, I am not 100% you are using "correlated" in the same sense I am. For you, I think it is our `Outputs`. For me, it is when there are actual correlation between properties.
